websea_chain_name = {
    'Ethereum Mainnet': 'ERC20',
    'Binance Smart Chain': 'BEP20',
    'BNB Smart Chain': 'BEP20',
    'Omnicore Mainnet': 'OMNI',
    'Tron Mainnet': 'TRC20',
    'Huobi Eco Chain': 'HRC20',
    'TRX': 'TRC20',
    'TRON': 'TRC20',
    'ETH': 'ERC20',
    'Ethereum': 'ERC20',
    'Bitcoin': 'BTC',
    'Celestia': 'TIA',
    'Toncoin': 'TON',
    'Sui Chain': 'SUI',
    'DogeCoin': 'DOGE',
    'Aptos Coin': 'APT',
    'Ripple': 'XRP',
    'Litecoin': 'LTC',
}
mxc_chain_name = {
    'ERC-20': 'ERC20',
    'TRC-20': 'TRC20',
    'BEP20(BSC)': 'BEP20',
    "BEP-20": 'BEP20',
    'BEP20（BSC）': 'BEP20',
    'BTM2': 'BTM',
    'TONCOIN': 'TON',
    'Polygon(MATIC)': 'Polygon',
    'SOL': 'SOLANA',
}
gate_chain_name = {
    'BRC': 'BRC20',
    'BSC': 'BEP20',
    'HT': 'HRC20',
    'ETH': 'ERC20',
    'TRC': 'TRC20',
    'MATIC': 'Polygon',
    'TRX': 'TRC20',
    'SOL': 'SOLANA',
    'OKBEVM': 'XLAYER',

}
huobi_chain_name = {
    'TRON': 'TRC20',
    'TRX': 'TRC20',
    'ETH': 'ERC20',
    'HECO': 'HRC20',
    'MATIC': 'Polygon',
}
okex_chain_name = {
    'TRON': 'TRC20',
    'TRX': 'TRC20',
    'ETH': 'ERC20',
    'BSC': 'BEP20',
    'Bitcoin': 'BTC',
    'Enjin Relay Chain': 'ENJ',
    'MATIC': 'Polygon',
    'Celestia': 'TIA',
    'Chiliz Chain': 'CHZ',
    'Dogecoin': 'DOGE',
    'Elrond': 'EGLD',
    'AELF': 'ELF',
    'Endurance Smart Chain': 'ENDURANCE',
    'Arbitrum One': 'ARBITRUM',
}
bitget_chain_name = {
    'TRON': 'TRC20',
    'TRX': 'TRC20',
    'ETH': 'ERC20',
    'IoTeX': 'IOTX',
    'MATIC': 'Polygon',
    'ChilizLegacyChain': 'CHZ',
    'INJECTIVE': 'INJ',
    'ArbitrumOne': 'Arbitrum',
    'zkSyncEra': 'zkSync Era',
    'ArbitrumNova': 'Arbitrum Nova',
    'Celestia': 'TIA',
    'ELROND': 'EGLD',
    'SOL': 'SOLANA',
}
balance_chain_name = {
    'Lightning Network': 'Lightning',
    'MATIC': 'Polygon',
    'SOL': 'SOLANA',
}
